### ISSUE TITLE
Implement Twitter's rules on characters

### ISSUE THREAD

**Issue by pnevares** [pnevares/twitter-splitter#1]
https://developer.twitter.com/en/docs/basics/counting-characters

**Comment by pnevares** [comment]
Already matches rules according to the New Tweet form

**Comment by pke** [comment]
Did you consider using the official [twitter-text](https://github.com/twitter/twitter-text/tree/master/js) package to calculate the length of each chunk?

**Comment by pnevares** [comment]
The package sounds familiar but I don't think I explored using it here. Are there some scenarios not covered that it would help with?

Skimming the docs it looks like I might be handling potentially-shortened URLs incorrectly!

**Comment by pke** [comment]
Yes calculating tweet length can be tricky with URLs and mentions and with the official lib they use to calculate we would be on the safe side.
So instead of checking the length of a given chunk of text oursselves we hand it to their lib and get back the exact length of the text.
Their lib would also give us always up to date max tweet length, so we could omit the splitter function limit argument (or set it by default to -1 to use max allowed tweet limit from their lib).
